name: PartyRTP
version: 0.8.0
main: net.morphedit.partyrtp.PartyRTPPlugin
api-version: '1.20'
author: MorphEdit
description: Party RTP Controller (works with any RTP plugin via command/provider)

commands:
  prtp:
    description: Party RTP command
    usage: /prtp
    permission: partyrtp.use

permissions:
  partyrtp.use:
    default: true
