name: PartyRTP
version: 0.9.0
main: net.morphedit.partyrtp.PartyRTPPlugin
api-version: '1.20'
author: MorphEdit
description: Party RTP Controller (works with any RTP plugin via command/provider)

commands:
  prtp:
    description: Party RTP command
    usage: /prtp
    permission: partyrtp.use

permissions:
  partyrtp.use:
    default: true
    description: Allows players to use party RTP features

  partyrtp.admin:
    default: op
    description: Gives access to all admin commands
    children:
      partyrtp.admin.reload: true
      partyrtp.admin.forcedisband: true
      partyrtp.admin.info: true
      partyrtp.admin.listall: true
      partyrtp.admin.debug: true

  partyrtp.admin.reload:
    default: op
    description: Allows reloading the configuration

  partyrtp.admin.forcedisband:
    default: op
    description: Allows force disbanding parties

  partyrtp.admin.info:
    default: op
    description: Allows viewing party information

  partyrtp.admin.listall:
    default: op
    description: Allows listing all parties

  partyrtp.admin.debug:
    default: op
    description: Allows toggling debug mode